[package]
name = "stardew-minifier"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
resolver = "2"
description = "Shrink Stardew Valley mod files by optimizing assets"

[dependencies]
anyhow = "1.0.43"
camino = "1.0.5"
encoding_rs = "0.8.28"
ignore = "0.4.18"
indicatif = { version = "0.16.2", features = ["rayon"] }
json5 = "0.3.0"
quick-xml = "0.22.0"
rayon = "1.5.1"
serde_json = "1.0.66"
structopt = "0.3.22"
tar = { version = "0.4.37", default-features = false }
tempfile = "3.2.0"
zip = { version = "0.5.13", default-features = false, features = ["deflate"] }
zstd = { version = "0.9.0", default-features = false }

[dependencies.oxipng]
version = "5.0.0"
default-features = false
features = ["binary", "filetime", "libdeflater"]

[profile.release]
lto = true
