[package]
name = "stardew-minifier"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
description = "Shrink Stardew Valley mod files by optimizing assets"

[dependencies]
anyhow = "1.0.65"
camino = "1.1.1"
clap = { version = "4.0.10", features = ["derive"] }
encoding_rs = "0.8.31"
ignore = "0.4.18"
indicatif = { version = "0.17.1", features = ["rayon"] }
json5 = "0.4.1"
quick-xml = "0.25.0"
rayon = "1.5.3"
serde_json = "1.0.85"
tar = { version = "0.4.38", default-features = false }
tempfile = "3.3.0"
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
zstd = { version = "0.11.2", default-features = false }

[dependencies.oxipng]
version = "6.0.1"
default-features = false
features = ["libdeflater"]

[profile.release]
lto = true
strip = true
