[package]
name = "stardew-minifier"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
description = "Shrink Stardew Valley mod files by optimizing assets"

[dependencies]
anyhow = "1.0.56"
camino = "1.0.7"
encoding_rs = "0.8.31"
ignore = "0.4.18"
indicatif = { version = "0.16.2", features = ["rayon"] }
json5 = "0.4.1"
quick-xml = "0.22.0"
rayon = "1.5.1"
serde_json = "1.0.79"
tar = { version = "0.4.38", default-features = false }
tempfile = "3.3.0"
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
zstd = { version = "0.11.1", default-features = false }
clap = { version = "3.1.8", features = ["derive"] }

[dependencies.oxipng]
version = "5.0.1"
default-features = false
features = ["binary", "filetime", "libdeflater"]

[profile.release]
lto = true
