[advisories]
ignore = [
    "RUSTSEC-2020-0071",
    "RUSTSEC-2022-0006",
]

[licenses]
allow = []
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "stardew-minifier", version = "*" },
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 },
]

[bans]
skip = [
    { name = "clap", version = "=2.34.0" },
    { name = "miniz_oxide", version = "=0.3.7" },
    { name = "strsim", version = "=0.8.0" },
    { name = "textwrap", version = "=0.11.0" },
]
