[licenses]
version = 2
allow = [
	"Apache-2.0",
	"BSD-3-Clause",
	"ISC",
	"MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "stardew-minifier" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
skip = [
    { name = "bitflags", version = "1" },
]
